export const navLinks =[
    {
        route:'/',
        label:'Home'
    },
    {
        route:'/forum',
        label:'CommunityQuotes'
    },
    {
        route:'/quote-creator',
        label:'Create'
    },
    {
        route:'/my-quotes',
        label:'MyQuotes'
    },
    {
        route:'/GoatQuotes',
        label:'GOATquotes'
    },
    {
        route:'/Profile',
        label:'Profile'
    },
]